Val loss: 3937.5411933765076	 Val error: 189001.97752192983
Epoch - 0	 step - 1266 	Train loss - 3904.565964792879 	 MAE - 3904.5659630586524
Val loss: 3870.2383112321822	 Val error: 185771.44325657896
/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py:96: UserWarning: Using a target size (torch.Size([1, 48])) that is different to the input size (torch.Size([48])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
Epoch - 1	 step - 1266 	Train loss - 3836.8256949625716 	 MAE - 3836.8256893745065
Val loss: 3805.9644475568803	 Val error: 182686.2931743421
Epoch - 2	 step - 1266 	Train loss - 3774.532439101655 	 MAE - 3774.5324331282063
Val loss: 3746.1712153919957	 Val error: 179816.22217653508
Epoch - 3	 step - 1266 	Train loss - 3716.636170541572 	 MAE - 3716.636163540433
Val loss: 3690.3064821477524	 Val error: 177134.71614583334
Epoch - 4	 step - 1266 	Train loss - 3662.5282052754415 	 MAE - 3662.5282072665914
Val loss: 3637.8640479372257	 Val error: 174617.4761513158
Epoch - 5	 step - 1266 	Train loss - 3611.634539019337 	 MAE - 3611.6345449285554
Val loss: 3588.287124366091	 Val error: 172237.7811129386
Epoch - 6	 step - 1266 	Train loss - 3563.695021535246 	 MAE - 3563.6950288575376
Val loss: 3541.6124674479165	 Val error: 169997.39569627194
Epoch - 7	 step - 1266 	Train loss - 3518.6898358110943 	 MAE - 3518.6898246349647
Val loss: 3497.928122001782	 Val error: 167900.54906798244
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    model = MLFFN(cfg,model.encoder)
  File "/home/atharva1511/Downloads/CS6910/assignment2/code2/model.py", line 29, in __init__
    self.AE=AE()
TypeError: 'Config' object is not callable
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    model = MLFFN(cfg,model.encoder)
  File "/home/atharva1511/Downloads/CS6910/assignment2/code2/model.py", line 29, in __init__
    self.AE=AE()
TypeError: 'Config' object is not callable
Epoch - 8	 step - 1266 	Train loss - 3476.296446260544 	 MAE - 3476.2964554455243
Val loss: 3456.7549085115133	 Val error: 165924.23697916666
Epoch - 9	 step - 1266 	Train loss - 3436.28062818327 	 MAE - 3436.2806228521276