Epoch - 0	 step - 1199 	Train loss - 0.6576152673612038 	 ACC - 0.6458333333333334
Val loss: 0.6425099316239357	 Val acc: 0.63
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    get_plot(model, trainloader, name = 'q2_done', title= 'q2_done')
  File "train.py", line 31, in get_plot
    print(true_outputs.shape())
TypeError: 'tuple' object is not callable
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    get_plot(model, trainloader, name = 'q2_done', title= 'q2_done')
  File "train.py", line 31, in get_plot
    print(true_outputs.shape())
TypeError: 'tuple' object is not callable