Val loss: 3937.5411933765076	 Val error: 189001.97752192983
Epoch - 0	 step - 1266 	Train loss - 3904.565964792879 	 MAE - 3904.5659630586524
1.0
/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py:96: UserWarning: Using a target size (torch.Size([1, 48])) that is different to the input size (torch.Size([48])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
/home/atharva1511/Downloads/CS6910/assignment2/code2/model.py:40: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y=self.soft(self.linear3(h2))
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    train_one_epoch2(model, trainloader, optimizer,
  File "train.py", line 87, in train_one_epoch2
    loss = criterion(output.squeeze(), target)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1163, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    train_one_epoch2(model, trainloader, optimizer,
  File "train.py", line 87, in train_one_epoch2
    loss = criterion(output.squeeze(), target)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1163, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)