TypeError: float() argument must be a string or a number, not 'DatasetReader1'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    train_dataset = sc.fit_transform(train_dataset)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 667, in fit
    return self.partial_fit(X, y)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 696, in partial_fit
    X = self._validate_data(X, accept_sparse=('csr', 'csc'),
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 598, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
TypeError: float() argument must be a string or a number, not 'DatasetReader1'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    train_dataset = sc.fit_transform(train_dataset)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/base.py", line 690, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 667, in fit
    return self.partial_fit(X, y)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 696, in partial_fit
    X = self._validate_data(X, accept_sparse=('csr', 'csc'),
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 598, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/home/atharva1511/.local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.